stages: 
  - build

cache:
  paths:
    - /home/se/.m2/repository/
    - target/

maven-package:
  stage: build
  script:
    - cp -r /home/se/dist ./src/main/resources/static/
    - mvn package -Dmaven.test.skip=true
    - cp -r target /home/se/target